@startuml classes
skinparam packageStyle rectangle
left to right direction

hide circle
hide methods

class User

User -down-> Judge
User -down-> Assessor

package "Dog rating system" {
    class Judge
    class Assessor

    ' class DRS
    ' Assessor -down-> DRS
    ' Judge -down-> DRS

    interface BreedRating
    interface DogDescription
    interface AcceptionToFamily

    Judge -- DogDescription
    Assessor -- BreedRating
    Assessor -- AcceptionToFamily

    ' DRS -- BreedRating
    ' DRS -- DogDescription
    ' DRS -- AcceptionToFamily

    package doc_DB <<Database>> {
        class word_doc1
        class word_doc2
        class word_doc3
        class word_doc4
    }

    DogDescription -- doc_DB
    BreedRating -- doc_DB
    AcceptionToFamily -- doc_DB
}


@enduml