@startuml Контекстная диаграмма C4: системы проведения племенного смотра

!include <C4/C4_Context>
!include <C4/C4_Container>

title Контекстная диаграмма системы судейства собачьих выставок
Person(user, "Пользователь", "Оценививающий эксперт")

System(system, "Система племенного смотра", "Веб-сервис для проведения кинологических мероприятий")

Rel(user, system, "Вводит данные собак, генерирует отчеты")

@enduml