@startuml "Пакетная диаграмма"

' package
' node
' folder
' frame
' cloud
' database

rectangle "Клиентский путь" {
    folder folder1 [
        This is a folder
        ----
        You can use separator
        ----
        of different kind
        ----
        and style
    ]

        folder folder2 [
        This is a folder
        ----
        You can use separator
        ----
        of different kind
        ----
        and style
    ]

        folder folder3 [
        This is a folder
        ----
        You can use separator
        ----
        of different kind
        ----
        and style
    ]
    
}
@enduml